import 'package:flutter/material.dart';

const List<Map<String, dynamic>> defaultWhiteNoiseSounds = [
  {
    'id': 'rain',
    'icon': Icons.umbrella_rounded,
    'name': '深山秋雨',
    'desc': '幽静山谷中的淅沥雨声，抚平内心焦虑。',
    'color': Colors.blueAccent,
    'url': '/static/audios/rain.mp3',
  },
  {
    'id': 'waves',
    'icon': Icons.waves_rounded,
    'name': '极地海浪',
    'desc': '远古冰川海滩上的潮汐起落，回归静止。',
    'color': Colors.cyanAccent,
    'url': '/static/audios/waves.mp3',
  },
  {
    'id': 'pines',
    'icon': Icons.forest_rounded,
    'name': '林间松涛',
    'desc': '微风穿过广阔针叶林，带来原野芬芳。',
    'color': Colors.greenAccent,
    'url': '/static/audios/pines.mp3',
  },
  {
    'id': 'fire',
    'icon': Icons.local_fire_department_rounded,
    'name': '壁炉篝火',
    'desc': '深夜小木屋里温暖柴火的噼啪爆裂碎响。',
    'color': Colors.orangeAccent,
    'url': '/static/audios/fire.mp3',
  },
  {
    'id': 'brook',
    'icon': Icons.water_rounded,
    'name': '山间溪流',
    'desc': '高山融雪化作林间欢快奔腾的潺潺清泉。',
    'color': Colors.tealAccent,
    'url': '/static/audios/brook.mp3',
  },
  {
    'id': 'insects',
    'icon': Icons.audiotrack_rounded,
    'name': '夏夜虫鸣',
    'desc': '繁星点点的仲夏夜里草丛间的自然协奏曲。',
    'color': Colors.amberAccent,
    'url': '/static/audios/insects.mp3',
  },
  {
    'id': 'wind',
    'icon': Icons.air_rounded,
    'name': '大漠狂风',
    'desc': '漫天黄沙掠过孤烟大漠的呼啸风声。',
    'color': Colors.grey,
    'url': '/static/audios/wind.mp3',
  },
  {
    'id': 'thunder',
    'icon': Icons.thunderstorm_rounded,
    'name': '雷鸣电闪',
    'desc': '乌云密布下的滚滚惊雷，感受大自然威力。',
    'color': Colors.deepPurpleAccent,
    'url': '/static/audios/thunder.mp3',
  },
  {
    'id': 'cafe',
    'icon': Icons.coffee_rounded,
    'name': '极客咖啡',
    'desc': '街角咖啡馆里轻声细语和咖啡杯的碰撞。',
    'color': Colors.brown,
    'url': '/static/audios/cafe.mp3',
  },
  {
    'id': 'train',
    'icon': Icons.train_rounded,
    'name': '列车轨响',
    'desc': '旅途中火车轮轨撞击的徐徐规律声律。',
    'color': Colors.blueGrey,
    'url': '/static/audios/train.mp3',
  },
  {
    'id': 'birds',
    'icon': Icons.flutter_dash_rounded,
    'name': '晨曦林鸟',
    'desc': '清晨森林深处百鸟争鸣，回归自然生机。',
    'color': Colors.lightGreenAccent,
    'url': '/static/audios/birds.mp3',
  },
  {
    'id': 'white_noise',
    'icon': Icons.blur_linear_rounded,
    'name': '纯白噪音',
    'desc': '均匀分布的白噪音，高效屏蔽外界杂音干扰。',
    'color': Colors.white,
    'url': '/static/audios/white_noise.mp3',
  },
  {
    'id': 'pink_noise',
    'icon': Icons.blur_on_rounded,
    'name': '粉红噪音',
    'desc': '低频更丰富的粉红噪音，更适合辅助安稳睡眠。',
    'color': Colors.pinkAccent,
    'url': '/static/audios/pink_noise.mp3',
  },
  {
    'id': 'keyboard',
    'icon': Icons.keyboard_rounded,
    'name': '机械键盘',
    'desc': '清脆有力的青轴击键声，激发创作灵感。',
    'color': Colors.purpleAccent,
    'url': '/static/audios/keyboard.mp3',
  },
  {
    'id': 'clock',
    'icon': Icons.av_timer_rounded,
    'name': '复古时钟',
    'desc': '老式摆钟规律的滴答声，带给内心沉静与秩序。',
    'color': Colors.redAccent,
    'url': '/static/audios/clock.mp3',
  },
  {
    'id': 'heartbeat',
    'icon': Icons.favorite_rounded,
    'name': '心跳共鸣',
    'desc': '温柔平缓的心跳律动，提供如母体般的安全感。',
    'color': Colors.red,
    'url': '/static/audios/heartbeat.mp3',
  },
  {
    'id': 'fan',
    'icon': Icons.wind_power_rounded,
    'name': '风扇低鸣',
    'desc': '炎炎夏日老风扇徐徐转动的白噪音低 hum 声。',
    'color': Colors.teal,
    'url': '/static/audios/fan.mp3',
  },
  {
    'id': 'airplane',
    'icon': Icons.flight_land_rounded,
    'name': '舱内气流',
    'desc': '万米高空飞机客舱内的平稳气流低回重音。',
    'color': Colors.indigoAccent,
    'url': '/static/audios/airplane.mp3',
  },
  {
    'id': 'underwater',
    'icon': Icons.water_drop_rounded,
    'name': '深海气泡',
    'desc': '潜入静谧海底，聆听水下微弱上升的水泡破碎声。',
    'color': Colors.blue,
    'url': '/static/audios/underwater.mp3',
  },
  {
    'id': 'snow',
    'icon': Icons.ac_unit_rounded,
    'name': '踏雪无声',
    'desc': '在松软雪地上一步步行走的咯吱咯吱解压碎响。',
    'color': Colors.lightBlueAccent,
    'url': '/static/audios/snow.mp3',
  },
  {
    'id': 'crickets',
    'icon': Icons.grass_rounded,
    'name': '溪畔蛐鸣',
    'desc': '潺潺流水边蛐蛐清脆吟唱，极具野趣的环境声景。',
    'color': Colors.lightGreen,
    'url': '/static/audios/crickets.mp3',
  },
];
